// Rendering the REVIEW ARTIFACT for a catalog promotion — the PR-comment template.
//
// Catalog additions are human-reviewed commits (Phase-A rule). This module renders what
// a reviewer reads: the proposed entry, the classifier fixture derived from the same
// bundle, and a checklist whose boxes a machine cannot tick. It renders a REFUSAL with
// equal prominence — a refused promotion produces a comment that says so, never silence,
// because a silently-absent comment is indistinguishable from a forgotten run.
//
// Nothing here writes a file or opens a PR. The output is text.

import type { CatalogEntry } from './catalog-schema';
import type { ClassifierFixture, IngestionOutcome, IngestionRefusal } from './ingestion';

/** Everything the rendered comment needs beyond the two ingestion outcomes. */
export interface PromotionContext {
	/** The runbook that captured the bundle (`RB-11` …) — the evidence's provenance. */
	readonly runbook: string;
	/** The repo-local evidence path the bundle was written to. */
	readonly evidencePath: string;
}

/** A promotion request: the two ingestion outcomes plus where the evidence came from. */
export interface PromotionRequest {
	readonly context: PromotionContext;
	readonly entry: IngestionOutcome<CatalogEntry>;
	readonly fixture: IngestionOutcome<ClassifierFixture>;
}

function refusalBlock(what: string, refusal: IngestionRefusal): string {
	return [
		`### ❌ ${what} — REFUSED`,
		'',
		`**Reason:** \`${refusal.reason}\``,
		'',
		`> ${refusal.detail}`,
		'',
		'This is a typed refusal from the ingestion seam, not a review opinion. Fix the',
		'capture and re-run the runbook; do not hand-author the artifact around it.',
	].join('\n');
}

function entryBlock(entry: CatalogEntry): string {
	return [
		'### Proposed `certified-catalog.json` entry',
		'',
		'```json',
		JSON.stringify(entry, null, 2),
		'```',
	].join('\n');
}

function fixtureBlock(fixture: ClassifierFixture): string {
	const { snapshot, provenance } = fixture;
	const syntheticNote = provenance.synthetic
		? '> ⚠️ Derived from a **synthetic** bundle — valid as test data, never as certification evidence.'
		: `> Derived from a real capture, bundle sha256 \`${provenance.bundleSha256}\`.`;
	return [
		'### Proposed classifier fixture (`control/src/backend/device-classifier.test.ts`)',
		'',
		syntheticNote,
		'',
		'```ts',
		`const FIXTURE: UsbDeviceSnapshot = ${JSON.stringify(snapshot, null, 2)};`,
		'```',
	].join('\n');
}

function checklistBlock(context: PromotionContext, entry: CatalogEntry): string {
	const transitions = entry.permittedTransitions.length;
	return [
		'### Reviewer checklist (every box is a human judgement)',
		'',
		`- [ ] The bundle at \`${context.evidencePath}\` was captured by **${context.runbook}** on real hardware, and its \`CERTIFY OK\` line reads \`synthetic=false\`.`,
		'- [ ] The bundle sha256 in the entry matches the sha256 the capture printed — recomputed, not copied from this comment.',
		`- [ ] \`canonicalMode: "${entry.canonicalMode}"\` is the mode the device was actually observed in, not the mode it was expected to be in.`,
		transitions === 0
			? '- [ ] `permittedTransitions: []` is correct for this stage — a stage-1 entry never declares a transition.'
			: '- [ ] The declared transition was OBSERVED end to end: the AT command executed, the port dropped if `expectsPortDrop`, and the device re-enumerated presenting `expectedDescriptors`.',
		'- [ ] No claim in `docs/MODEM-SUPPORT-MATRIX.md` is being changed by this commit without its own evidence.',
	].join('\n');
}

/**
 * Render the review comment for a promotion request. Always returns a comment: a
 * refusal renders a refusal block, so a run that produced nothing promotable still
 * leaves a visible, auditable trace.
 */
export function renderPromotionReview(request: PromotionRequest): string {
	const { context, entry, fixture } = request;
	const parts: string[] = [
		`## Catalog promotion review — ${context.runbook}`,
		'',
		`Evidence: \`${context.evidencePath}\``,
		'',
		'Generated by the `control/src/usb-mode/` ingestion seam. **This comment promotes',
		'nothing** — the promotion is the human-reviewed commit that follows it.',
		'',
	];

	parts.push(entry.ok ? entryBlock(entry.value) : refusalBlock('Catalog entry', entry));
	parts.push('');
	parts.push(
		fixture.ok ? fixtureBlock(fixture.value) : refusalBlock('Classifier fixture', fixture),
	);
	parts.push('');
	if (entry.ok) {
		parts.push(checklistBlock(context, entry.value));
	} else {
		parts.push(
			'### No checklist',
			'',
			'The catalog entry was refused, so there is nothing to review. A checklist here',
			'would invite a reviewer to approve an artifact that does not exist.',
		);
	}
	return `${parts.join('\n')}\n`;
}
