// The matrix summary artifact.
//
// A conformance suite that only goes green tells a reviewer that nothing broke and
// nothing else. The artifact is the other half: every case, its kind, the decision it
// was ENTITLED to and the decision it actually got, in a form a human reads and a later
// todo (29's CeraUI migration, 42's hardware bench certification) can diff against.
//
// It lands in the repo-local, gitignored `test-results/` — evidence, never a tracked
// file, and never a path above this checkout root (AGENTS.md § Rule D).

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { ConformanceExpectation, ConformanceKind } from './cases';

export type MatrixRow = {
	readonly id: string;
	readonly kind: ConformanceKind;
	readonly summary: string;
	readonly expected: ConformanceExpectation;
	readonly actual: ConformanceExpectation;
	readonly agrees: boolean;
};

const ARTIFACT_DIR = resolve(import.meta.dir, '../../../test-results');
export const MATRIX_JSON_PATH = resolve(ARTIFACT_DIR, 'provider-conformance-matrix.json');
export const MATRIX_MARKDOWN_PATH = resolve(ARTIFACT_DIR, 'provider-conformance-matrix.md');

function decision(value: ConformanceExpectation): string {
	const target = value.provider === null ? '—' : `${value.provider} / ${value.profile}`;
	return `${value.status} · ${target} · ${value.writable ? 'writable' : 'read-only'} · ${value.score}`;
}

function markdown(rows: readonly MatrixRow[]): string {
	const byKind = new Map<ConformanceKind, number>();
	for (const row of rows) byKind.set(row.kind, (byKind.get(row.kind) ?? 0) + 1);
	const lines = [
		'# Provider-matching conformance matrix',
		'',
		`Cases: **${rows.length}** · agreeing: **${rows.filter((row) => row.agrees).length}** · ` +
			`writable selections: **${rows.filter((row) => row.actual.writable).length}**`,
		'',
		'Generated by `control/src/providers/conformance-matrix.test.ts`. Every row runs the real',
		'matcher with the ModemManager, Huawei HiLink, ZTE goform and UFI/HIMI providers all',
		'registered at once.',
		'',
		'| # | Case | Kind | Expected decision | Actual decision | Agrees |',
		'|---|------|------|-------------------|-----------------|--------|',
		...rows.map(
			(row, index) =>
				`| ${index + 1} | \`${row.id}\`<br>${row.summary} | ${row.kind} | ${decision(row.expected)} | ${decision(row.actual)} | ${row.agrees ? 'yes' : '**NO**'} |`,
		),
		'',
		'## Cases by kind',
		'',
		'| Kind | Cases |',
		'|------|-------|',
		...[...byKind.entries()].map(([kind, count]) => `| ${kind} | ${count} |`),
		'',
	];
	return `${lines.join('\n')}\n`;
}

/** Write both artifact forms and return the markdown, so a caller can assert on it. */
export function writeMatrixArtifact(rows: readonly MatrixRow[]): string {
	const document = markdown(rows);
	mkdirSync(dirname(MATRIX_JSON_PATH), { recursive: true });
	writeFileSync(
		MATRIX_JSON_PATH,
		`${JSON.stringify({ caseCount: rows.length, rows }, null, '\t')}\n`,
	);
	writeFileSync(MATRIX_MARKDOWN_PATH, document);
	return document;
}
